name: Build

on:
  push:
    branches: [ "main" ]
    tags: '*'
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build-bookmarker-api:
    name: Build bookmarker-api
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./bookmarker-api

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 19
        uses: actions/setup-java@v3
        with:
          java-version: '19'
          distribution: 'corretto'
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Execute Gradle Build
        run: ./gradlew check

      - if: ${{ startsWith(github.ref, 'refs/tags/') }} # only with tag pushes TODO: remove ref/main
        name: Build Docker Image
        run: |
          ./gradlew clean build -x check
          docker build . --file Dockerfile --tag ${{ secrets.DOCKER_USERNAME }}/bookmarker-api:${{ github.ref_name }}
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker push ${{ secrets.DOCKER_USERNAME }}/bookmarker-api:${{ github.ref_name }}